[ID-29][ID-22][ID-33]Feat circular menu canvas
suesitran/interactive_diary pull request #104
Opened 2022-11-16 08:52 UTC by DongNguyenQ

2022-11-16 09:05 UTC, suesitran requested changes
Please remove those unexpected files

2022-11-16 09:05 UTC, suesitran commented on lib/features/home/widgets/google_map.dart
> +const String menuVoiceMarkerLocationId = 'menuVoiceMarkerLocationId';
Shouldn't all the ID strings end with Id?

2022-11-16 09:05 UTC, suesitran commented on lib/features/home/widgets/google_map.dart
> +              print('BASE MARKER CLICKED');
Please avoid print(), you can use debugPrint() instead

2022-11-16 09:05 UTC, suesitran commented on lib/features/home/widgets/google_map.dart
> +            (Marker element) => element.markerId.value != 'currentLocation');
I think this currentLocation ID can be defined as constant as well

2022-11-16 09:05 UTC, suesitran commented on lib/features/home/widgets/google_map.dart
> +              print('menuCameraMarkerLocation');
Avoid using print

2022-11-16 09:05 UTC, suesitran commented on lib/features/home/widgets/google_map.dart
> +              print('menuPencilMarkerLocation');
Same

2022-11-16 09:05 UTC, suesitran commented on lib/features/home/widgets/google_map.dart
> +              print('menuEmojiMarkerLocation');
Same

2022-11-16 09:05 UTC, suesitran commented on lib/features/home/widgets/google_map.dart
> +              print('menuVoiceMarkerLocation');
Same

2022-11-16 09:05 UTC, suesitran commented on lib/generated/intl/messages_all.dart
> +// Ignore issues from commonly used lints in this file.
Something is not right with this file. There should be many strings in here. 

You can choose to NOT commit this file, or commit the file with all strings in it.

2022-11-16 09:05 UTC, suesitran commented on lib/generated/intl/messages_en.dart
> +// ignore_for_file:unnecessary_brace_in_string_interps, unnecessary_new
Same as above

2022-11-16 09:05 UTC, suesitran commented on packages/nartus_ui_package/ios/Flutter/Generated.xcconfig
> +// This is a generated file; do not edit or check into version control.
Please do not commit this file to repo

2022-11-16 09:05 UTC, suesitran commented on packages/nartus_ui_package/ios/Flutter/flutter_export_environment.sh
> +# This is a generated file; do not edit or check into version control.
Please do not commit this file to repo

2022-11-16 09:05 UTC, suesitran commented on packages/nartus_ui_package/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
> +// This is a generated file; do not edit or check into version control.
Please do not commit this file to repo

2022-11-16 09:05 UTC, suesitran commented on packages/nartus_ui_package/macos/Flutter/ephemeral/flutter_export_environment.sh
> +# This is a generated file; do not edit or check into version control.
Please do not commit this file to repo

2022-11-16 12:20 UTC, DongNguyenQ commented on packages/nartus_ui_package/ios/Flutter/Generated.xcconfig
> +// This is a generated file; do not edit or check into version control.
@suesitran it's weird that i didn't commit those files, i think it was committed when i pull new update from repo

2022-11-21 06:23 UTC, suesitran approved these changes

2022-11-21 06:25 UTC, merged