Koc/no internet connection
suesitran/interactive_diary pull request #111
Opened 2022-12-01 04:24 UTC by lqchuong

2022-12-01 07:14 UTC, lqchuong commented on packages/nartus_connectivity/lib/src/nartus_connectivity_plus_impl.dart
> -  final StreamController<bool> _connectivityChange = StreamController();
I edited here because I got error "[StreamBuilder. Bad state: Stream has already been listened to [duplicate]]" when listening Stream in bloc

2022-12-01 11:01 UTC, suesitran requested changes
please update your branch and resolve conflict

2022-12-01 11:01 UTC, suesitran commented on lib/bloc/connectivity/connectivity_bloc.dart
> +  final ConnectivityPlusServiceImpl _connectivity;
please use the abstract class here: ConnectivityService

2022-12-01 11:01 UTC, suesitran commented on lib/bloc/connectivity/connectivity_bloc.dart
> +    print("12345678");
avoid print in production

2022-12-01 11:01 UTC, suesitran commented on lib/bloc/location/location_bloc.dart
> +    LatLng(10.7725, 106.6980); //location nhà thờ đức bà
nope, default location is at Ben Thanh market

2022-12-01 11:01 UTC, suesitran commented on lib/constants/map_style.dart
> +enum MapStyle {
why is this a new file? it's already added to our code base

2022-12-01 11:01 UTC, suesitran commented on lib/features/home/home_screen.dart
> +              Navigator.of(context).push(MaterialPageRoute(
please use GoRouter here

2022-12-01 11:01 UTC, suesitran commented on lib/features/home/home_screen.dart
> +              Navigator.of(context).push(MaterialPageRoute(
please use GoRouter here

2022-12-01 11:01 UTC, suesitran commented on lib/features/home/widgets/google_map.dart
>      _generateMarkerIcon();
why is there a change here? what happens to circular menu implementation?

2022-12-09 16:47 UTC, DongNguyenQ reviewed
Look good to me

2022-12-10 00:36 UTC, merged