ID-124 [UI] - Diary detail - Text only
suesitran/interactive_diary pull request #165
Opened 2023-05-07 13:36 UTC by lqchuong

2023-05-08 10:02 UTC, suesitran requested changes
1. lib/features/diary_detail/widgets/content_card_appbar.dart is not needed
2. Do not pass Documents through Route

2023-05-08 10:02 UTC, suesitran commented on lib/features/diary_detail/diary_detail_screen.dart
> +    Future<void>.delayed(const Duration(milliseconds: 500))
why do we need a cheat here? do we have keyboard usage in this screen?

2023-05-08 10:02 UTC, suesitran commented on lib/features/diary_detail/diary_detail_screen.dart
> +              readOnly: false,
this is a detail display, so we need this screen to be readOnly

2023-05-08 10:02 UTC, suesitran commented on lib/features/diary_detail/diary_detail_screen.dart
> +class _DiaryDetailBodyState extends State<DiaryDetailBody> {
why do we need a StatefulWidget here?

2023-05-08 10:02 UTC, suesitran commented on lib/features/diary_detail/widgets/content_card_appbar.dart
> +class ContentCardAppBarView extends StatefulWidget {
why do we need StatefulWidget here?

2023-05-08 10:02 UTC, suesitran commented on lib/features/diary_detail/widgets/content_card_appbar.dart
> +      child: Column(
there's only 1 widget, why do we need Column here?

2023-05-08 10:02 UTC, suesitran commented on lib/features/diary_detail/widgets/content_card_appbar.dart
> +class _ContentCardAppBarViewState extends State<ContentCardAppBarView> {
return single child, so we do not need a widget to wrap outside of it

2023-05-08 10:02 UTC, suesitran commented on lib/features/diary_detail/widgets/diary_header.dart
> +                      semanticsLabel: S.current.diaryDateFormatter(
semantic label is same as text, so it's not needed

2023-05-08 10:02 UTC, suesitran commented on lib/features/home/bloc/load_diary_cubit.dart
> +  final StorageService storageService =
i dont think u need to edit this file for this story

2023-05-08 10:02 UTC, suesitran commented on lib/features/home/content_panel/contents_bottom_panel_view.dart
> +                                              context.gotoDiaryDetailScreen(e),
do not pass the full DiaryContent in route

2023-05-08 10:02 UTC, suesitran commented on lib/features/home/data/diary_display_content.dart
> +  final Document? document;
NO, do not pass the full document to a display data

2023-05-08 10:06 UTC, lqchuong commented on lib/features/diary_detail/diary_detail_screen.dart
> +class _DiaryDetailBodyState extends State<DiaryDetailBody> {
i think we need update some features in future, for example: when you click likes, number of likes...

2023-05-08 10:12 UTC, lqchuong commented on lib/features/home/bloc/load_diary_cubit.dart
> +  final StorageService storageService =
sr, i think my IDE edit it automatically, i will revert it

2023-05-08 10:15 UTC, lqchuong commented on lib/features/diary_detail/widgets/content_card_appbar.dart
> +      child: Column(
because first there were 2 widgets, but when i removed 1 widget, i forgot to delete Column

2023-05-11 02:36 UTC, suesitran requested changes

2023-05-11 02:36 UTC, suesitran commented on lib/features/diary_detail/bloc/diary_detail_cubit.dart
> +    QuillController richText = QuillController(
QuillController is a UI component, it should not be in a cubit, you can pass the json text from db to UI, and use Document and QuillController on UI to display

2023-05-11 02:36 UTC, suesitran commented on lib/features/diary_detail/bloc/diary_detail_cubit.dart
> +    String plainText = document.toPlainText();
I dont think we need plain text in diary detail screen

2023-05-11 02:36 UTC, suesitran commented on lib/features/diary_detail/bloc/diary_detail_cubit.dart
> +    Document? document = Document.fromJson(textJson);
I think i made mistake to use Document in load_diary_cubit, it belongs to Quill, which is a UI component.

2023-05-11 02:36 UTC, suesitran commented on lib/features/diary_detail/bloc/diary_detail_state.dart
> +  final QuillController richText;
remove QuillController here

2023-05-11 02:36 UTC, suesitran commented on lib/features/diary_detail/diary_detail_screen.dart
> +class _DiaryDetailBodyState extends State<DiaryDetailBody> {
when we need it we'll use it, right now we do not need StatefulWidget

2023-05-11 02:36 UTC, suesitran commented on lib/features/diary_detail/diary_detail_screen.dart
> +    return BlocConsumer<DiaryDetailCubit, DiaryDetailState>(
BlocConsumer is not needed here, we do not need any action listener yet. When the future comes, we'll add, for now, do not use it.

2023-05-11 02:36 UTC, suesitran commented on lib/features/diary_detail/diary_detail_screen.dart
> +          if (state is LoadDiaryDetailCompleted) {
please do not use BlocBuilder on the whole screen. Apply BlocBuilder where the UI needs it. In this case, BlocBuilder is needed around QuillEditor

2023-05-11 02:36 UTC, suesitran commented on lib/features/diary_detail/widgets/diary_header.dart
> +              CircleAvatar(
maybe we need ExcludeSemantic here

2023-05-11 03:40 UTC, suesitran commented on lib/features/diary_detail/bloc/diary_detail_cubit.dart
> +    Document? document = Document.fromJson(textJson);
please do not follow my mistake, and remove Document from cubit

2023-05-11 13:04 UTC, suesitran requested changes
only 1 issue left

2023-05-11 13:04 UTC, suesitran commented on lib/features/home/content_panel/widgets/diary_header.dart
> +  final String dateFormat = 'dd MMM, yyyy';
why do we have 2 diary_header.dart? I think the layout are the same right? We just need 1 right?

2023-05-16 01:51 UTC, suesitran approved these changes, later dismissed

2023-05-16 09:39 UTC, suesitran approved these changes, later dismissed

2023-05-22 20:19 UTC, suesitran approved these changes

2023-05-22 20:20 UTC, merged

2023-06-20 12:50 UTC, binhpd commented on lib/features/diary_detail/diary_detail_screen.dart
> +    List<Map<String, Object>> textJson = [
extract to generate data method

2023-06-20 12:58 UTC, binhpd commented on lib/features/diary_detail/diary_detail_screen.dart
> +    String timeFormat = 'HH:mm a';
Use instance variable

2023-06-20 13:14 UTC, binhpd commented on lib/features/diary_detail/diary_detail_screen.dart
> +    Document? document = Document.fromJson(textJson);
Handle null or empty data